image: node:8

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
  only:
    - master

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    - dpl --provider=heroku --app=<heroku app name> --api-key=<heroku api key>
